Beer.create(
  [
    { name: 'BREWDOG ブリュードッグ　4種12本飲み比べセット　ギフト　クラフトビール',
      url: 'https://www.amazon.co.jp/dp/B017GS9V26' },
    { name: '「馨和 KAGUA」Blanc & Rouge 6本セット　330ml × 6本',
      url: 'https://www.amazon.co.jp/dp/B00G3YJMZQ' },
    { name: '【世界が認めた新潟の地ビール】 スワンレイク クラフトビール 金賞 6本 330ml 飲み比べ ギフトセット',
      url: 'https://www.amazon.co.jp/dp/B00V5M8KHW' },
    { name: '常陸野ネストビール12本ギフトセット',
      url: 'http://www.amazon.co.jp/dp/B0093IQWI4' },
    { name: '【常陸野ネストビール】だいだいエール入り 常陸野ネスト12本セット',
      url: 'https://www.amazon.co.jp/dp/B00MNXKWEG' },
    { name: 'アンカー・リバティーエール 355ml×24本',
      url: 'https://www.amazon.co.jp/dp/B004VQDJBG' },
    { name: '【 セット 販売 】 ANCHOR ( アンカー ) ポーター ビール 355ml × 6本',
      url: 'https://www.amazon.co.jp/dp/B007K3SU6G' },
    { name: '[スコットランド ブリュードッグ] パンク IPA 330ml 6本 [BREWDOG PUNK IPA 330ml]',
      url: 'https://www.amazon.co.jp/dp/B00IAIV7XS' },
    { name: 'COEDO コエドビール 330ml × 10本 飲み比べセット（ 伽羅3：瑠璃3：白2：紅赤1：漆黒1 ',
      url: 'https://www.amazon.co.jp/dp/B00BN4BXS0' },
    { name: 'キリン ドラフトギネス 24本',
      url: 'https://www.amazon.co.jp/dp/B004P9FF1G' },
    { name: 'ブルックリンラガー 24本',
      url: 'https://www.amazon.co.jp/dp/B008XRMR7Q' },
    { name: 'ブリュードッグ ブラックハマー ブラックＩＰＡ 330ml 24本 1ケース BREWDOG BLACK HAMMER',
      url: 'https://www.amazon.co.jp/dp/B01LE878SI' },
    { name: 'アメリカお土産 アンカースチーム エール 6本セット',
      url: 'https://www.amazon.co.jp/dp/B00DS06I2S' },
    { name: 'ハロウィン限定 【クラフトビール 8種 330ml × 8本飲み比べセット＜ハロウィンラベル ビール入＞】 8本全てが違う味！',
      url: 'https://www.amazon.co.jp/dp/B0052B5S7C' },
    { name: '富士桜高原麦酒１２本セット（ピルス・ヴァイツェン・ラオホ・シュヴァルツヴァイツェン各３本ずつ） ',
      url: 'https://www.amazon.co.jp/dp/B00IP3ZIMY' },
    { name: 'ドゥシャス・デ・ブルゴーニュ 330ml×24本 (DUCHESSE DE BOURGOGNE)',
      url: 'https://www.amazon.co.jp/dp/B007M6RUNU' }
  ]
)
